apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagina-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagina-web
  template:
    metadata:
      labels:
        app: pagina-web
    spec:
      containers:
        - name: pagina-web
          image: ignaciosa/front:ce2a9385e0a3ab6e330d4d46217cc5f3c507367c
          ports:
            - containerPort: 80
          env:
            - name: backend-url
              value: /api
