apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ignaciosa/back:ce2a9385e0a3ab6e330d4d46217cc5f3c507367c
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: usuario
            - name: DB_PASSWORD
              value: "1908"
            - name: DB_NAME
              value: golgana
